# Generated by Django 5.2.7 on 2026-02-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, null=True, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='route',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10, null=True, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterUniqueTogether(
            name='routeschedule',
            unique_together={('route', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
