# Generated by Django 5.2.7 on 2026-02-03 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_routeschedule_day_of_week_alter_route_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la comunidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='routeschedule',
            unique_together={('route', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='routeschedule',
            name='day_of_week',
        ),
        migrations.CreateModel(
            name='RouteCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignada el')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_routes', to='core.community')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_communities', to='core.route')),
            ],
            options={
                'verbose_name': 'Comunidad por Ruta',
                'verbose_name_plural': 'Comunidades por Ruta',
                'unique_together': {('route', 'community')},
            },
        ),
    ]
