# Generated by Django 5.2.7 on 2026-02-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_community_alter_routeschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de borrado'),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_by_user',
            field=models.BooleanField(default=False, verbose_name='Borrado por usuario'),
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_globally',
            field=models.BooleanField(default=False, verbose_name='Borrado por admin (global)'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['usuario', 'created_at'], name='core_notifi_usuario_8ee0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['deleted_globally', 'created_at'], name='core_notifi_deleted_cb0602_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['deleted_by_user', 'created_at'], name='core_notifi_deleted_a517f1_idx'),
        ),
    ]
