# Generated by Django 5.2.7 on 2026-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notification_options_notification_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routeschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='routeschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=10, verbose_name='Día de la semana'),
        ),
        migrations.AlterUniqueTogether(
            name='routeschedule',
            unique_together={('route', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
